namespace csShared.Geo
{
  public enum MapType {
    Google_Maps,
    Google_Satellite,
    Google_Terrain,
    Google_Gray,
    Google_Light_Gray,
    Google_Dark_Gray,
    Google_Traffic,
    MapQuest,
    Skobbler,
    Open_Cycle_Map,
    Bing_Roads,
    Bing_Aerial,
    Open_Street_Map,
    Water_Color,
    Toner,
    Night,
    Mapbox_Streets,
    Mapbox_Light_Blue,
    Mapbox_Blue_Gray,
    Mapbox_Terrain,
    Cloud_Made,
    Red_Alert,
    Water_vs_Land,
    Midnight,
    Fresh,
    Clean
  }
}
