//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//   Runtime Version:4.0.30319.17929
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csShared.Properties {
    /// <summary>
  ///  A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  internal class CoordinateTypes {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal CoordinateTypes() {
    }
    
    /// <summary>
    ///  Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
      get {
        if (object.ReferenceEquals(resourceMan, null)) {
          global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("csShared.Properties.CoordinateTypes", typeof(CoordinateTypes).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }
    
    /// <summary>
    ///  Overrides the current thread's CurrentUICulture property for all
    ///  resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
      get {
        return resourceCulture;
      }
      set {
        resourceCulture = value;
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to DMS.
    /// </summary>
    internal static string COORDINATE_FORMAT_DEGREEMINUTESECOND {
      get {
        return ResourceManager.GetString("COORDINATE_FORMAT_DEGREEMINUTESECOND", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to Degrees.
    /// </summary>
    internal static string COORDINATE_FORMAT_DEGREES {
      get {
        return ResourceManager.GetString("COORDINATE_FORMAT_DEGREES", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to Rijksdriehoek.
    /// </summary>
    internal static string COORDINATE_FORMAT_RD {
      get {
        return ResourceManager.GetString("COORDINATE_FORMAT_RD", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to Unknown.
    /// </summary>
    internal static string COORDINATE_FORMAT_UNKNOWN {
      get {
        return ResourceManager.GetString("COORDINATE_FORMAT_UNKNOWN", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to XY.
    /// </summary>
    internal static string COORDINATE_FORMAT_XY {
      get {
        return ResourceManager.GetString("COORDINATE_FORMAT_XY", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to Latitude.
    /// </summary>
    internal static string COORDINATE_LABEL_DEGREEMINUTESECOND_NS {
      get {
        return ResourceManager.GetString("COORDINATE_LABEL_DEGREEMINUTESECOND_NS", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to Longitude.
    /// </summary>
    internal static string COORDINATE_LABEL_DEGREEMINUTESECOND_WE {
      get {
        return ResourceManager.GetString("COORDINATE_LABEL_DEGREEMINUTESECOND_WE", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to Latitude.
    /// </summary>
    internal static string COORDINATE_LABEL_DEGREES_NS {
      get {
        return ResourceManager.GetString("COORDINATE_LABEL_DEGREES_NS", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to Longitude.
    /// </summary>
    internal static string COORDINATE_LABEL_DEGREES_WE {
      get {
        return ResourceManager.GetString("COORDINATE_LABEL_DEGREES_WE", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to Rd-Y.
    /// </summary>
    internal static string COORDINATE_LABEL_RD_NS {
      get {
        return ResourceManager.GetString("COORDINATE_LABEL_RD_NS", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to Rd-X.
    /// </summary>
    internal static string COORDINATE_LABEL_RD_WE {
      get {
        return ResourceManager.GetString("COORDINATE_LABEL_RD_WE", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to Unknown.
    /// </summary>
    internal static string COORDINATE_LABEL_UNKNOWN {
      get {
        return ResourceManager.GetString("COORDINATE_LABEL_UNKNOWN", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to Y.
    /// </summary>
    internal static string COORDINATE_LABEL_XY_NS {
      get {
        return ResourceManager.GetString("COORDINATE_LABEL_XY_NS", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to X.
    /// </summary>
    internal static string COORDINATE_LABEL_XY_WE {
      get {
        return ResourceManager.GetString("COORDINATE_LABEL_XY_WE", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to latitude.
    /// </summary>
    internal static string COORDINATE_STRING_DEGREEMINUTESECOND_NS {
      get {
        return ResourceManager.GetString("COORDINATE_STRING_DEGREEMINUTESECOND_NS", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to longitude.
    /// </summary>
    internal static string COORDINATE_STRING_DEGREEMINUTESECOND_WE {
      get {
        return ResourceManager.GetString("COORDINATE_STRING_DEGREEMINUTESECOND_WE", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to latitude.
    /// </summary>
    internal static string COORDINATE_STRING_DEGREES_NS {
      get {
        return ResourceManager.GetString("COORDINATE_STRING_DEGREES_NS", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to longitude.
    /// </summary>
    internal static string COORDINATE_STRING_DEGREES_WE {
      get {
        return ResourceManager.GetString("COORDINATE_STRING_DEGREES_WE", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to rd-Y.
    /// </summary>
    internal static string COORDINATE_STRING_RD_NS {
      get {
        return ResourceManager.GetString("COORDINATE_STRING_RD_NS", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to rd-X.
    /// </summary>
    internal static string COORDINATE_STRING_RD_WE {
      get {
        return ResourceManager.GetString("COORDINATE_STRING_RD_WE", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to unknown.
    /// </summary>
    internal static string COORDINATE_STRING_UNKNOWN {
      get {
        return ResourceManager.GetString("COORDINATE_STRING_UNKNOWN", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to Y.
    /// </summary>
    internal static string COORDINATE_STRING_XY_NS {
      get {
        return ResourceManager.GetString("COORDINATE_STRING_XY_NS", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to X.
    /// </summary>
    internal static string COORDINATE_STRING_XY_WE {
      get {
        return ResourceManager.GetString("COORDINATE_STRING_XY_WE", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to The {0} must be specified!.
    /// </summary>
    internal static string MESSAGE_COORDINATE_NOT_SPECIFIED {
      get {
        return ResourceManager.GetString("MESSAGE_COORDINATE_NOT_SPECIFIED", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to The specified {0} is out of range! Range is [{1}...{2}]..
    /// </summary>
    internal static string MESSAGE_COORDINATE_OUT_OF_RANGE {
      get {
        return ResourceManager.GetString("MESSAGE_COORDINATE_OUT_OF_RANGE", resourceCulture);
      }
    }
    
    /// <summary>
    ///  Looks up a localized string similar to The specified {0} has an unknown format!.
    /// </summary>
    internal static string MESSAGE_COORDINATE_UNKNOWN_FORMAT {
      get {
        return ResourceManager.GetString("MESSAGE_COORDINATE_UNKNOWN_FORMAT", resourceCulture);
      }
    }
  }
}
